### ISSUE TITLE
如何确保gnet.Conn有效？

### ISSUE THREAD

**Issue by LeeGaning** [panjf2000/gnet#126]
```go
func (es *echoServer) React(frame []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	// Echo synchronously.
	// out = frame
	// return

	// Echo asynchronously.
	log.Printf("%s->%s,RX:[% x]", c.RemoteAddr(), c.LocalAddr(), frame)
	// data := append([]byte{}, frame...)
	if es.async {
		data := append([]byte{}, frame...)
		_ = es.workerPool.Submit(func() {
			time.Sleep(time.Second)
			 //if c.RemoteAddr() != nil {
			//log.Printf("%s->%s,TX:[% x]", c.RemoteAddr(), c.LocalAddr(), data)
			c.AsyncWrite(data)
			//}
		})
		return
	}
	return
}
```
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x68e72b]

goroutine 8 [running]:
main.(*echoServer).OnClosed(0xc00012e580, 0x7a46c0, 0xc000134be0, 0x0, 0x0, 0x0)
	C:/MyProgram/Project/golang/102_server/main.go:36 +0x6b
github.com/panjf2000/gnet.(*eventloop).loopCloseConn(0xc00004e120, 0xc000134be0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/leega/go/pkg/mod/github.com/panjf2000/gnet@v1.2.9/eventloop_unix.go:199 +0x492
github.com/panjf2000/gnet.(*eventloop).loopRead(0xc00004e120, 0xc000134be0, 0x12, 0xc00016e168)
	C:/Users/leega/go/pkg/mod/github.com/panjf2000/gnet@v1.2.9/eventloop_unix.go:127 +0xcf
github.com/panjf2000/gnet.(*eventloop).handleEvent(0xc00004e120, 0x12, 0x1, 0x0, 0xc00023c000)
	C:/Users/leega/go/pkg/mod/github.com/panjf2000/gnet@v1.2.9/loop_linux.go:38 +0x88
github.com/panjf2000/gnet/internal/netpoll.(*Poller).Polling(0xc000058140, 0xc000110f80, 0x0, 0x0)
	C:/Users/leega/go/pkg/mod/github.com/panjf2000/gnet@v1.2.9/internal/netpoll/epoll.go:102 +0x143
github.com/panjf2000/gnet.(*eventloop).loopRun(0xc00004e120)
	C:/Users/leega/go/pkg/mod/github.com/panjf2000/gnet@v1.2.9/eventloop_unix.go:68 +0x95
github.com/panjf2000/gnet.(*server).startEventLoops.func1.1(0xc00004e120, 0xc00016e000)
	C:/Users/leega/go/pkg/mod/github.com/panjf2000/gnet@v1.2.9/server_unix.go:73 +0x2b
created by github.com/panjf2000/gnet.(*server).startEventLoops.func1
	C:/Users/leega/go/pkg/mod/github.com/panjf2000/gnet@v1.2.9/server_unix.go:72 +0x6a

```
接收使用了自定义codec，异步处理任务时，处理任务后回送报文出现RemoteAddr()为nil，回复panic。
windows平台也是同样的。

**Comment by iHDJ** [comment]
我一般会监听OnClose，然后在conn.Context()里面标记session.closed = true

**Comment by panjf2000** [comment]
你这种情况大概是 conn 提前关闭了而你的异步任务还没有执行完，如果是这样的话，在 `OnClosed` 事件函数中标记 conn 并没有用，因为之后 conn 的信息会被清空释放：
https://github.com/panjf2000/gnet/blob/abbf5820c1d264fa22e8bf8d00755d6093a86767/connection_unix.go#L72-L85
另外，一般来说，异步任务完成要把数据写回客户端是调用 `AsyncWrite`，这个方法会在真正写数据之前检查 conn 是否可用，如果已经关闭了就不会写数据了，确保了不会发生错误，所以通常来说也不会有报错，不知道你在异步任务里使用 RemoteAddr 是要做什么？

我觉得你应该找出 conn 提前关闭的原因，正常的设计应该是要确保 conn 在业务逻辑完成之前都是可用的，不管是同步还是异步，现在 conn 提前关闭了，是因为你主动设置了 timeout，还是因为其他意料之外的错误？如果是刻意设置主动断开连接的，考虑到现在存在异步任务未完成而 conn 就主动断开了的情况，如果这种情况频繁出现，那么你需要重新思考这种设计是否合理。

**Comment by LeeGaning** [comment]
@panjf2000 是这样，conn在异步执行完之前就由于客户端断开了。现实中这种情况conn断开是很常见的，比如客户端网络突然中断。
正因为如此我使用了`AsyncWrite`。多次测试，在没有增加自定义codec的时候，conn断开后再调用`AsyncWrite`方法是可以的。增加自定义codec之后，就会出错（例程也是这样）
```shell
2020/08/14 09:01:31 192.168.1.230:48521 closed.EOF
2020/08/14 09:01:31 192.168.1.230:48522 connected.
2020/08/14 09:01:31 192.168.1.230:48522->[::]:9933,RX:[01 13 00 00 20 01 00 3E 12 02 26 10 10 00 ]
2020/08/14 09:01:31 %!s(<nil>)->%!s(<nil>),TX:[01 13 00 00 20 01 00 3E 12 02 26 10 10 00 ]
2020-08-14T09:01:31.928+0800	INFO	gnet@v1.2.8/eventloop_windows.go:77	Event-loop(0) is exiting due to the error: write tcp 192.168.1.235:9933->192.168.1.230:48521: use of closed network connection
2020-08-14T09:01:31.928+0800	INFO	gnet@v1.2.8/server_windows.go:107	Server is being shutdown on the signal error: write tcp 192.168.1.235:9933->192.168.1.230:48521: use of closed network connection
2020-08-14T09:01:31.929+0800	INFO	gnet@v1.2.8/eventloop_windows.go:77	Event-loop(3) is exiting due to the error: server is going to be shutdown
2020-08-14T09:01:31.929+0800	INFO	gnet@v1.2.8/eventloop_windows.go:77	Event-loop(2) is exiting due to the error: server is going to be shutdown
2020-08-14T09:01:31.929+0800	INFO	gnet@v1.2.8/eventloop_windows.go:77	Event-loop(1) is exiting due to the error: server is going to be shutdown
2020/08/14 09:01:31 192.168.1.230:48522 closed.read tcp 192.168.1.235:9933->192.168.1.230:48522: i/o timeout
2020/08/14 09:01:31 <nil>
```

**Comment by panjf2000** [comment]
和有没有 codec 应该没关系，AsyncWrite 在真正写数据之前会判断一下 c.opened，如果是 false 根本不会调用 write 函数，也就不会使用 codec，而且你说的出错是是指什么？还有你说 Linux 下似乎没有这个问题，那你到底是哪个 OS 上跑的？把相关信息贴一下吧，Go 版本，gnet 版本，OS。

**Comment by panjf2000** [comment]
长时间未回复，暂时关闭，如果还有问题可以随时重新打开。
