### ISSUE TITLE
下面情况奔溃，麻烦大佬们看看为啥？

### ISSUE THREAD

**Issue by FJSDS** [panjf2000/gnet#301]
```go
package main

import (
	"encoding/binary"
	"fmt"
	"sync/atomic"
	"time"

	"github.com/panjf2000/gnet"
)

type client struct {
	gnet.EventServer
	gnetClient *gnet.Client
}

var count int64

func (this_ *client) React(packet []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	if len(packet) > 8 {
		panic(111)
	}
	x := binary.LittleEndian.Uint64(packet)
	x1 := c.Context().(uint64)
	if x != x1 {
		panic(fmt.Sprintf("expected %d,actual %d", x1, x))
	}
	x1++
	c.SetContext(x1)
	atomic.AddInt64(&count, 1)
	return
}
func (this_ *client) OnClosed(c gnet.Conn, err error) (action gnet.Action) {
	fmt.Println(c.Context(), c.LocalAddr(), err)
	return
}

func (this_ *client) Dail(addr string) {
	c, err := this_.gnetClient.Dial("tcp", addr)
	must(err)
	c.SetContext(uint64(0))
	go func() {
		index := uint64(0)
		for {
			ub := make([]byte, 8)
			binary.LittleEndian.PutUint64(ub, index)
			must(c.AsyncWrite(ub))
			index++
			time.Sleep(time.Microsecond)
		}
	}()
}

func NewClient() *client {
	c := &client{}
	gc, err := gnet.NewClient(c, gnet.WithCodec(gnet.NewFixedLengthFrameCodec(8)), gnet.WithTCPKeepAlive(time.Second*30))
	must(err)
	c.gnetClient = gc
	_ = gc.Start()
	return c
}

var addr = "127.0.0.1:9922"

func must(err error) {
	if err != nil {
		panic(err)
	}
}

var mc = map[*client]struct{}{}

func main() {

	s := &Server{}
	go func() {
		must(gnet.Serve(s, addr, gnet.WithReusePort(true), gnet.WithMulticore(true), gnet.WithCodec(gnet.NewFixedLengthFrameCodec(8))))
	}()

	time.Sleep(time.Second)
	for i := 0; i < 6; i++ {
		StartClient()
	}

	oldCount := int64(0)
	for {
		ct := atomic.LoadInt64(&count)
		fmt.Println(ct, ct-oldCount)
		oldCount = ct
		time.Sleep(time.Second)
	}
}

func StartClient() {
	c := NewClient()
	for i := 0; i < 10; i++ {
		c.Dail(addr)
	}
	mc[c] = struct{}{}
}

type Server struct {
	gnet.EventServer
}

func (this_ *Server) OnOpened(c gnet.Conn) (out []byte, action gnet.Action) {
	fmt.Println(c.RemoteAddr())
	return
}
func (this_ *Server) React(packet []byte, c gnet.Conn) (out []byte, action gnet.Action) {
	must(c.AsyncWrite(packet))
	return
}

func (this_ *Server) OnClosed(c gnet.Conn, err error) (action gnet.Action) {
	fmt.Println("server", c.RemoteAddr(), err)
	return
}

```

painc info :
```
127.0.0.1:53830
127.0.0.1:53832
127.0.0.1:53834
127.0.0.1:53836
127.0.0.1:53838
127.0.0.1:53840
127.0.0.1:53842
0 127.0.0.1:53840 <nil>
server 127.0.0.1:53840 read: connection reset by peer
127.0.0.1:53844
server 127.0.0.1:53830 read: connection reset by peer
108 127.0.0.1:53830 <nil>
81 127.0.0.1:53832 <nil>
server 127.0.0.1:53832 read: connection reset by peer
0 127.0.0.1:53834 <nil>
server 127.0.0.1:53834 <nil>
0 127.0.0.1:53836 <nil>
server 127.0.0.1:53836 read: connection reset by peer
0 127.0.0.1:53838 <nil>
panic: expected 0,actual 61

goroutine 34 [running]:
main.(*client).React(0xc000422000, {0xc000310398, 0xc0000c6140, 0x200000003}, {0x608ec0, 0xc0000c6140})
        /home/fj/workspace/test/main.go:26 +0x154
github.com/panjf2000/gnet.(*eventloop).loopRead(0xc00042e070, 0xc0000c6140)
        /home/fj/gopath/pkg/mod/github.com/panjf2000/gnet@v1.6.1/eventloop_unix.go:128 +0x164
github.com/panjf2000/gnet.(*eventloop).loopRun.func2(0x587140, 0x1)
        /home/fj/gopath/pkg/mod/github.com/panjf2000/gnet@v1.6.1/reactor_default_linux.go:130 +0xe5
github.com/panjf2000/gnet/internal/netpoll.(*Poller).Polling(0xc000428000, 0xc000117f88)
        /home/fj/gopath/pkg/mod/github.com/panjf2000/gnet@v1.6.1/internal/netpoll/epoll_default_poller.go:136 +0x2da
github.com/panjf2000/gnet.(*eventloop).loopRun(0xc00042e070, 0x0)
        /home/fj/gopath/pkg/mod/github.com/panjf2000/gnet@v1.6.1/reactor_default_linux.go:104 +0xcb
github.com/panjf2000/gnet.(*Client).Start.func1()
        /home/fj/gopath/pkg/mod/github.com/panjf2000/gnet@v1.6.1/client.go:100 +0x2d
created by github.com/panjf2000/gnet.(*Client).Start
        /home/fj/gopath/pkg/mod/github.com/panjf2000/gnet@v1.6.1/client.go:99 +0xa7

Process finished with the exit code 2

```

**Comment by FJSDS** [comment]
@panjf2000

**Comment by panjf2000** [comment]
server 端的 React() 为什么要调 AsyncWrite？这样顺序可能会乱，还有，c.Context()/c.SetContext() 只能在事件函数里调用，不能 dial 之后直接用，多看看文档。

**Comment by panjf2000** [comment]
还有，下次开 issue 按模板填信息，不然下次我直接关掉。

**Comment by FJSDS** [comment]
> 还有，下次开 issue 按模板填信息，不然下次我直接关掉。

好的，多谢

**Comment by FJSDS** [comment]
看了源码才晓得，要在OnOpen 调用了才能发送消息。
